### ISSUE TITLE
Different date format on startText & endText

### ISSUE THREAD

**Issue by erhansaydam** [Innologica/vue2-daterange-picker#12]
Hi,

Can you add a feature to let changing the date format of startText & endText values. In my country it is used as DD-MM-YYYY.

Thank you,
Best regards.

**Comment by nkostadinov** [comment]
There is a prop of the picker that can change the format of the dates. I will document it now, since then you can set the format of the dates via :
`:locale-data="{ format: moment.localeData().longDateFormat('L') }"`

moment.localeData().longDateFormat('L') is the default value which is based on the current locale of moment js.

**Comment by nkostadinov** [comment]
The compoentn did not respected the format in localeData. I've fixed it and updated the demo to format 'DD-MM-YYYY'. 
Update to version 0.1.1 and check again
