### ISSUE TITLE
Display option

### ISSUE THREAD

**Issue by tchret** [Innologica/vue2-daterange-picker#154]
Is there any way to display the date picker outside of the popover?

**Comment by nkostadinov** [comment]
you mean like inline ?

**Comment by buremba** [comment]
@nkostadinov There is no date range picker library that supports inline editors at the moment so this feature would be really useful for the community. It looks like the calendars are visible only on the popover, can you add a prop something like `inline` so that we can embed the calendar into the page directly: Here is an example:

![image](https://user-images.githubusercontent.com/82745/81385527-24290000-911c-11ea-8ecc-8f7fde4d8ad6.png)

**Comment by nkostadinov** [comment]
Well, the inline option is on my todo list so it will happen eventually :) . I really think it will be nice addition

**Comment by buremba** [comment]
Thanks, @nkostadinov! Please close this issue when it's implemented so that we can switch from Element UI datepicker to this library. :) Really loved the simplicity, the only mature date picker component is v-calendar at the moment and it's 250kb minified. :/

**Comment by buremba** [comment]
Thanks, @nkostadinov ! I will try to use the library today when I have time. :)

**Comment by tchret** [comment]
Thanks man
