### ISSUE TITLE
Even if I set date-util to 'date-fns', webpack will still package moment.

### ISSUE THREAD

**Issue by zhnoah** [Innologica/vue2-daterange-picker#166]
What did I do wrong?

**Comment by nkostadinov** [comment]
hmm, it is only required in devDependcies. And it should not be included in the production build if you dont use it.

**Comment by vedmant** [comment]
I have the same problem, it always includes moment.js in the package.

**Comment by JJBocanegra** [comment]
I'm having the same problem, the output size is around 360KB because of moment localisations, that size is too much :(

**Comment by ggondim** [comment]
Apparently the file [src/components/util.js](https://github.com/Innologica/vue2-daterange-picker/blob/master/src/components/util.js#L5) does a dynamic `require` but when the library is built it is packaged alongside this other libraries. Even when specified `optionalDependencies` and `peerDependencies`, modules are imported in utils' files and these options don't affect the final bundle because dynamic `require` can't be determined as "tree-shakeable". 

The best solution is to separate them into alternative packages (such as "@vue2-daterange-picker/moment") to make this library unopionated.

**I've made a pull request with this package proposal.**

Additional util packages were published under `@vue2-daterange-picker/moment` and `@vue2-daterange-picker/date-fns`.

For now, until this PR is merged, I published a temporary package under npm without this packaged files. Install it using [`npm install @ggondim-org/vue2-daterange-picker`](https://www.npmjs.com/package/@ggondim-org/vue2-daterange-picker). 

UMD file was reduced to 184KB (78% smaller, was 861KB).

**Before**:
![image](https://user-images.githubusercontent.com/2074685/86875267-76ed4c80-c0b8-11ea-8de6-f3ffcd93aaca.png)

**After**:
![image](https://user-images.githubusercontent.com/2074685/86875056-05150300-c0b8-11ea-829c-d078f2566af4.png)

I think `dateformat.js` also needs to be externalized using it's [npm package](https://www.npmjs.com/package/dateformat) to be optimized.

**Comment by nkostadinov** [comment]
removed the dependencies. you can use whatever you like just pass date object or timestamp to the picker. Will release new version soon.
